#!/bin/bash
# Warble Linux — make-and-bake
#
# Builds ISO (real mkarchiso when available) + release artifacts.
# On hosts without archiso (e.g. Ubuntu CI), produces valid non-empty *mock*
# artifacts so GitHub Releases never see 0-byte files.
#
# Usage:
#   EDITION=1 ./scripts/make-and-bake.sh
#   EDITION=4 MOCK_ONLY=1 ./scripts/make-and-bake.sh
#   make edition=2
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Prefer explicit VERSION, then VERSION file (semver X.Y.Z), then UTC date
if [[ -z "${VERSION:-}" ]]; then
  if [[ -f "$ROOT/VERSION" ]]; then
    VERSION="$(tr -d '[:space:]' <"$ROOT/VERSION")"
  else
    VERSION="$(date -u +%Y.%m.%d)"
  fi
fi
GIT_SHA="${GIT_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo local)}"
WORK_DIR="${WORK_DIR:-/tmp/warble-linux-work}"
OUT_DIR="${OUT_DIR:-$ROOT/out}"
PROFILE_DIR="$ROOT/profile"
EDITIONS_DIR="$ROOT/editions"
MOCK_ONLY="${MOCK_ONLY:-0}"

log() { printf '==> %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# ── Edition selection ────────────────────────────────────────────────────────
if [[ -z "${EDITION:-}" ]]; then
  if command -v dialog >/dev/null 2>&1 && [[ -t 0 ]]; then
    EDITION=$(dialog --clear \
      --backtitle "Warble Linux" \
      --title "Select edition" \
      --menu "Sandbox variant:" 16 75 5 \
      1 "Minimal (desktop + terminal)" \
      2 "Developer (Go, Rust, Python, Node)" \
      3 "Cloud-Native (Docker, kubectl, helm)" \
      4 "Full (Developer + Cloud-Native)" \
      2>&1 >/dev/tty) || true
    clear || true
  else
    EDITION=1
    log "No TTY/dialog — defaulting EDITION=1 (minimal)"
  fi
fi

case "$EDITION" in
  1|2|3|4) ;;
  *) die "invalid EDITION=$EDITION (use 1-4)" ;;
esac

EDITION_NAME=("" "minimal" "developer" "cloud-native" "full")
ENAME="${EDITION_NAME[$EDITION]}"
log "Edition $EDITION ($ENAME)  version=$VERSION  sha=$GIT_SHA"

# ── Compose packages.x86_64 from editions/ ───────────────────────────────────
mkdir -p "$PROFILE_DIR"
PKG_FILE="$PROFILE_DIR/packages.x86_64"
EDITION_PKG="$EDITIONS_DIR/${ENAME}.packages"
BASE_PKG="$EDITIONS_DIR/base.packages"

[[ -f "$BASE_PKG" ]] || die "missing $BASE_PKG"
[[ -f "$EDITION_PKG" ]] || die "missing $EDITION_PKG"

{
  echo "# Generated by scripts/make-and-bake.sh — do not edit by hand"
  echo "# edition=$ENAME ($EDITION) version=$VERSION"
  echo "#"
  # Strip comments/blank lines; unique preserve order
  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "")
      if (!seen[$0]++) print
    }
  ' "$BASE_PKG" "$EDITION_PKG"
} > "$PKG_FILE"

log "Wrote $(grep -cve '^#' -e '^$' "$PKG_FILE" || true) packages → profile/packages.x86_64"

# ── Build ISO ────────────────────────────────────────────────────────────────
rm -rf "$WORK_DIR"
mkdir -p "$OUT_DIR" "$WORK_DIR"
ISO_NAME="warble-linux-${ENAME}-${VERSION}-${GIT_SHA}.iso"
ISO_PATH="$OUT_DIR/$ISO_NAME"

build_real_iso() {
  command -v mkarchiso >/dev/null 2>&1 || return 1
  [[ -f "$PROFILE_DIR/profiledef.sh" ]] || return 1
  [[ -f "$PROFILE_DIR/pacman.conf" ]] || {
    log "profile/pacman.conf missing — cannot run real mkarchiso yet"
    return 1
  }
  # Bootloader trees are still WIP; refuse if clearly incomplete
  if [[ ! -d "$PROFILE_DIR/syslinux" && ! -d "$PROFILE_DIR/grub" ]]; then
    log "profile lacks syslinux/ and grub/ — real bake needs releng-style bootloaders (see docs/building.md)"
    return 1
  fi
  log "Running mkarchiso (real ISO)..."
  mkarchiso -v -w "$WORK_DIR" -o "$OUT_DIR" "$PROFILE_DIR"
  local found
  found=$(ls -1 "$OUT_DIR"/*.iso 2>/dev/null | head -1 || true)
  if [[ -n "$found" && "$found" != "$ISO_PATH" ]]; then
    mv -f "$found" "$ISO_PATH"
  fi
  [[ -s "$ISO_PATH" ]] || return 1
  return 0
}

build_mock_iso() {
  log "Creating non-empty mock ISO (mkarchiso unavailable, incomplete profile, or MOCK_ONLY=1)"
  local stage="$WORK_DIR/mock-iso-root"
  rm -rf "$stage"
  mkdir -p "$stage/warble-linux"
  cat > "$stage/warble-linux/README.txt" <<EOF
Warble Linux — MOCK ARTIFACT (not a bootable ISO)

Edition:  $EDITION ($ENAME)
Version:  $VERSION
Git:      $GIT_SHA
Built:    $(date -u +%Y-%m-%dT%H:%M:%SZ)

This file is produced without a complete archiso profile / mkarchiso.
For a real ISO on Arch Linux:
  sudo pacman -S archiso
  # complete profile bootloaders (see docs/building.md)
  make edition=$EDITION

https://github.com/warble-tech/warble-linux
EOF
  cp "$PKG_FILE" "$stage/warble-linux/packages.x86_64" 2>/dev/null || true
  if command -v genisoimage >/dev/null 2>&1; then
    genisoimage -quiet -o "$ISO_PATH" -V "WARBLE_MOCK" -J -R "$stage"
  elif command -v mkisofs >/dev/null 2>&1; then
    mkisofs -quiet -o "$ISO_PATH" -V "WARBLE_MOCK" -J -R "$stage"
  elif command -v xorriso >/dev/null 2>&1; then
    xorriso -as mkisofs -o "$ISO_PATH" -V "WARBLE_MOCK" -J -R "$stage" >/dev/null 2>&1
  else
    tar -C "$stage" -czf "$ISO_PATH" warble-linux
  fi
  [[ -s "$ISO_PATH" ]] || echo "warble-linux mock" > "$ISO_PATH"
}

if [[ "$MOCK_ONLY" == "1" ]]; then
  build_mock_iso
elif ! build_real_iso; then
  build_mock_iso
fi

# ── Secondary artifacts ──────────────────────────────────────────────────────
log "Generating WSL / OVF / Vagrant / manifest artifacts..."

WSL="$OUT_DIR/warble-linux-wsl2-${ENAME}-${VERSION}.tar.gz"
OVF="$OUT_DIR/warble-linux-${ENAME}-${VERSION}.ovf"
BOX="$OUT_DIR/warble-linux-${ENAME}-${VERSION}.box"
MANIFEST="$OUT_DIR/MANIFEST-${ENAME}-${VERSION}.txt"
SHAFILE="$OUT_DIR/SHA256SUMS-${ENAME}-${VERSION}.txt"

WSL_STAGE="$WORK_DIR/wsl-root"
rm -rf "$WSL_STAGE"
mkdir -p "$WSL_STAGE/etc" "$WSL_STAGE/usr/local/bin" "$WSL_STAGE/root"
echo "Warble Linux WSL mock rootfs edition=$ENAME version=$VERSION" > "$WSL_STAGE/etc/warble-release"
{
  echo "ID=warble-linux"
  echo "NAME=\"Warble Linux\""
  echo "VERSION=$VERSION"
  echo "VARIANT=$ENAME"
} > "$WSL_STAGE/etc/os-release"
printf '#!/bin/sh\necho warble-linux wsl mock\n' > "$WSL_STAGE/usr/local/bin/warble-hello"
chmod +x "$WSL_STAGE/usr/local/bin/warble-hello"
tar -C "$WSL_STAGE" -czf "$WSL" .

cat > "$OVF" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Warble Linux OVF stub — attach real disk after full image bake -->
<Envelope xmlns="http://schemas.dmtf.org/ovf/envelope/1"
          xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1">
  <References>
    <File ovf:id="iso" ovf:href="$(basename "$ISO_PATH")" ovf:size="$(stat -c%s "$ISO_PATH" 2>/dev/null || echo 0)"/>
  </References>
  <DiskSection>
    <Info>Warble Linux Live ISO reference</Info>
  </DiskSection>
  <VirtualSystem ovf:id="Warble-Linux-${ENAME}">
    <Info>Warble Linux ${ENAME} ${VERSION}</Info>
    <Name>Warble-Linux-${ENAME}</Name>
  </VirtualSystem>
</Envelope>
EOF

BOX_STAGE="$WORK_DIR/box"
rm -rf "$BOX_STAGE"
mkdir -p "$BOX_STAGE"
cat > "$BOX_STAGE/metadata.json" <<EOF
{"provider":"virtualbox","format":"ovf","version":"0"}
EOF
echo "Warble Linux Vagrant box stub edition=$ENAME version=$VERSION" > "$BOX_STAGE/Vagrantfile"
echo "# Placeholder — replace with real disk.vmdk after full bake" > "$BOX_STAGE/box.ovf"
tar -C "$BOX_STAGE" -czf "$BOX" metadata.json Vagrantfile box.ovf

MOCK_FLAG=no
if [[ "$MOCK_ONLY" == "1" ]] || ! command -v mkarchiso >/dev/null 2>&1; then
  MOCK_FLAG=yes
elif [[ ! -d "$PROFILE_DIR/syslinux" && ! -d "$PROFILE_DIR/grub" ]]; then
  MOCK_FLAG=yes
fi

{
  echo "Warble Linux build manifest"
  echo "edition=$ENAME ($EDITION)"
  echo "version=$VERSION"
  echo "git=$GIT_SHA"
  echo "built_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "host=$(uname -a)"
  echo "mock=$MOCK_FLAG"
  echo "iso=$(basename "$ISO_PATH")"
  echo "wsl=$(basename "$WSL")"
  echo "ovf=$(basename "$OVF")"
  echo "box=$(basename "$BOX")"
  echo "packages_file=profile/packages.x86_64"
} > "$MANIFEST"

(
  cd "$OUT_DIR"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$(basename "$ISO_PATH")" "$(basename "$WSL")" "$(basename "$OVF")" "$(basename "$BOX")" > "$(basename "$SHAFILE")"
  else
    shasum -a 256 "$(basename "$ISO_PATH")" "$(basename "$WSL")" "$(basename "$OVF")" "$(basename "$BOX")" > "$(basename "$SHAFILE")"
  fi
)

log "Artifact sizes:"
fail=0
for f in "$ISO_PATH" "$WSL" "$OVF" "$BOX" "$MANIFEST" "$SHAFILE"; do
  if [[ ! -s "$f" ]]; then
    echo "  EMPTY: $f" >&2
    fail=1
  else
    sz=$(wc -c <"$f" | tr -d ' ')
    echo "  OK ($sz bytes): $(basename "$f")"
  fi
done
(( fail == 0 )) || die "one or more artifacts are empty — GitHub Releases would reject them"

log "Build complete → $OUT_DIR"
ls -la "$OUT_DIR"
echo ""
echo "Edition: $ENAME | mock=$MOCK_FLAG"
echo "Docs: docs/building.md | https://github.com/warble-tech/warble-linux"
