name: Publish to GCP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make and Bake ISO
      run: |
        export EDITION=4
        ./make-and-bake.sh

    - name: Create GitHub Release and Upload Artifacts
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "nightly-${{ github.sha }}"
        name: "Nightly Build"
        files: out/*
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
